In [31]:
import numpy as np

a = np.array([0,2,0])
B = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
c = np.array([1, 2, 3])

In [32]:
a / c

array([ 0.,  1.,  0.])

In [27]:
B[np.arange(B.shape[0]),a]

array([1, 6, 7])

In [28]:
B[np.arange(B.shape[0]),a] = 0
print(B)

[[0 2 3]
 [4 5 0]
 [0 8 9]]


In [30]:
np.sum(B > 0, axis=1)

array([2, 2, 2])